name: Lint & Test Shell Scripts

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  test-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bats

      - name: ShellCheck
        run: shellcheck $(find . -name "*.sh")

      - name: Run Bats Tests
        run: bats tests
